### ISSUE TITLE
Support skipping KMS keys

### ISSUE THREAD

**Issue by ben-harvey** [mitre/aws-foundations-cis-baseline#109]
This improvement would allow skipping a list of KMS keys defined by the user in the `inputs.yml`, in the same manner as security groups and S3 buckets.  One possible implementation would look like: 
```yml
  - name: exception_keys_list
    description: 'list of KMS keys exempted from inspection'
    type: Array
    value:
      - 'exception_key_alias' (or 'exception_key_id', if that makes more sense)
```

To clarify a use case, ITOPS configures certain KMS keys for ADOs.  ADOs don't have IAM permissions to perform actions on these keys, which leads to warnings like: 
```
WARN: AWS Service Error encountered running a control with Resource aws_kms_key. Error message: User: arn:aws:iam::{account}:user/{user} is not authorized to perform: kms:GetKeyRotationStatus on resource: arn:aws:kms:us-east-1:{account}:key/{id} because no resource-based policy allows the kms:GetKeyRotationStatus action. You should address this error to ensure your controls are behaving as expected.
```
