### ISSUE TITLE
control# 4.4 Improved approach

### ISSUE THREAD

**Issue by karikarshivani** [mitre/aws-foundations-cis-baseline#96]
We could update this check to be more meaningful with input values
1) Suggested input value style
```
  - name: peering_connection_ids
    description: 'peering connection ids'
    type: hash
    value:
      pcx-1a2b3c4d:
        destinationcidrblock: '10.2.0.0/16'
      pcx-2a2b3c4d:
        destinationcidrblock: '10.4.0.0/16'
```

2) Test could be updated to something like below (code below not tested)
```
      describe route do
        its([:vpc_peering_connection_id]) { should be_in peering_connection_ids.keys }
        its([:destination_cidr_block]) { should_not be peering_connection_ids[route.vpc_peering_connection_id] }

      end

```
3) Update generate_attributes script to query and fill out peering_connection_ids hash in the right format

_Originally posted by @rx294 in https://github.com/mitre/cis-aws-foundations-baseline/pull/95#discussion_r475567791_
